// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPCcOI9m8KNHyBGmypjJ4z8zLUlxXlVWc',
    appId: '1:707990130657:web:02d0edce80648722dccca0',
    messagingSenderId: '707990130657',
    projectId: 'uniconnect-133ae',
    authDomain: 'uniconnect-133ae.firebaseapp.com',
    storageBucket: 'uniconnect-133ae.firebasestorage.app',
    measurementId: 'G-7YSZ6WG74H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH1UATdWID_RihxQpDoVreQyDICEo4XhY',
    appId: '1:707990130657:android:2e4f3780468e2499dccca0',
    messagingSenderId: '707990130657',
    projectId: 'uniconnect-133ae',
    storageBucket: 'uniconnect-133ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1JKReG_yKor7ng2nUQ720Ab4UoLCPZCY',
    appId: '1:707990130657:ios:c8fe440c4d1cd79adccca0',
    messagingSenderId: '707990130657',
    projectId: 'uniconnect-133ae',
    storageBucket: 'uniconnect-133ae.firebasestorage.app',
    iosBundleId: 'com.example.uniconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1JKReG_yKor7ng2nUQ720Ab4UoLCPZCY',
    appId: '1:707990130657:ios:c8fe440c4d1cd79adccca0',
    messagingSenderId: '707990130657',
    projectId: 'uniconnect-133ae',
    storageBucket: 'uniconnect-133ae.firebasestorage.app',
    iosBundleId: 'com.example.uniconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPCcOI9m8KNHyBGmypjJ4z8zLUlxXlVWc',
    appId: '1:707990130657:web:6fc59e230ef6648adccca0',
    messagingSenderId: '707990130657',
    projectId: 'uniconnect-133ae',
    authDomain: 'uniconnect-133ae.firebaseapp.com',
    storageBucket: 'uniconnect-133ae.firebasestorage.app',
    measurementId: 'G-KBZ0L25N7C',
  );
}
